stream {
    server {
        listen 3306;
        server_name domain1.com;
        proxy_pass 127.0.0.1:3306;
    }
}

stream {
    server {
        listen 3306;
        server_name domain2.com;
        proxy_pass 127.0.0.1:3307;
    }
}
