server {
    listen 80;
    server_name domain1.com;

    location / {
        proxy_pass http://backend_server1;
        # Other proxy settings if needed
    }
}

server {
    listen 443;
    server_name domain2.com;
    ssl_certificate /etc/nginx/certs/proxy_server.crt;
    ssl_certificate_key /etc/nginx/certs/proxy_server.key;
    
    location / {
        proxy_pass http://backend_server2;
        # Other proxy settings if needed
    }
}

# Add more server blocks for additional domains


stream {
    map $ssl_preread_server_name $backend {
        domain1.com backend_server1:443;
        domain2.com backend_server2:443;
        # Add more mappings for additional domains and backend addresses
        default backend_default:443;
    }

    server {
        listen 443;
        proxy_pass $backend;
        ssl_preread on;

        # SSL certificate and key for the proxy server
        ssl_certificate /etc/nginx/certs/proxy_server.crt;
        ssl_certificate_key /etc/nginx/certs/proxy_server.key;
    }
}
