stream {
    map $ssl_preread_server_name $mysql_backend {
        domain1.com mysql_backend_server1:3306;
        domain2.com mysql_backend_server2:3306;
        # Add more mappings for additional domains and backend addresses
        default mysql_backend_default:3306;
    }

    server {
        listen 3306;
        proxy_pass $mysql_backend;
        ssl_preread on;
    }
}
