apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: debian:bullseye-slim
      command:
        - sh
        - -c
        - |
          apt-get update && \
          apt-get install -y curl iputils-ping dnsutils && \
          sleep infinity
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
  restartPolicy: Always
