apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-user-crb
subjects:
  - kind: ServiceAccount
    name: sa-user
    namespace: devops  # Add this line to specify the namespace
roleRef:
  kind: ClusterRole
  name: clusterrole-name
  apiGroup: rbac.authorization.k8s.io
---
# kubectl create token sa-user -n devops

# apiVersion: v1
# kind: Secret
# metadata:
#   name: sa-user-token
#   namespace: devops
#   annotations:
#     kubernetes.io/service-account.name: "sa-user"
# type: kubernetes.io/service-account-token

# kubectl get secret sa-user-token -n devops -o jsonpath="{.data.token}" | base64 --decode
